Numpy Array Operations

In [10]:
import numpy as np

Indexing

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Indexing:", arr[2:6])
print("Step Indexing:", arr[1:8:2])
print("Negative Indexing:", arr[-5])

Basic Indexing: [3 4 5 6]
Step Indexing: [2 4 6 8]
Negative Indexing: 5


2D Indexing

In [16]:
arr_2d = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print("Specific element:", arr_2d[2,2])
# print("Specific element:", arr_2d[row,element])
print("Entire Row:", arr_2d[1])
print("Entire Column:", arr_2d[:,1])


Specific element: 11
Entire Row: [5 6 7 8]
Entire Column: [ 2  6 10]


Sorting

In [21]:
unsorted_array = np.array([1,4,5,7,2,4,9,8,6,4,2,])
print("Sorted Array:", np.sort(unsorted_array))

unsorted_array_2d = np.array([[1,3,4],
                              [2,6,2],
                              [1,9,6]])
print("Sorted Array 2D:", np.sort(unsorted_array_2d))
print("Sorted Array 2D by column:", np.sort(unsorted_array_2d, axis=0))

Sorted Array: [1 2 2 4 4 4 5 6 7 8 9]
Sorted Array 2D: [[1 3 4]
 [2 2 6]
 [1 6 9]]
Sorted Array 2D by column: [[1 3 2]
 [1 6 4]
 [2 9 6]]


Filtering

In [22]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers:", even_numbers)

Even Numbers: [ 2  4  6  8 10]


Filter with mask

In [23]:
mask = numbers > 6
print("Numbers greater than 6:", numbers[mask])

Numbers greater than 6: [ 7  8  9 10]


Fancy indexing vs np.where()

In [24]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


Adding and removing data

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]
