Numpy array and basics

In [2]:
import numpy as np

Creating array from list

In [5]:
array_1d = np.array([1,2,3,4,5,6])
print("Array_1D :", array_1d)

array_2d = ([[1,2,3], [4,5,6]])
print("Array_2D :", array_2d)
# the array parameter requires a single array otherwise it gives a error

Array_1D : [1 2 3 4 5 6]
Array_2D : [[1, 2, 3], [4, 5, 6]]


multiplication

In [6]:
arr = np.array([1,2,3,4,5])
print(arr*2)

[ 2  4  6  8 10]


Python List VS Numpy array

In [9]:
py_list = [1,2,3,4]
print("Python list multiplication:", py_list * 2)

np_array = np.array([1,2,3,4])
print("Numpy array multiplication:" , np_array*2)

Python list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
Numpy array multiplication: [2 4 6 8]


Time Calculation

In [12]:
import time
Start  = time.time()
py_list = [i*2 for i in range (1000000)]
print("\n List operation time:", time.time() - Start)

Start = time.time()
np_array = np.arange(1000000)*2
print("\n Array operation time:", time.time() - Start)


 List operation time: 0.2061605453491211

 Array operation time: 0.00928807258605957


Creating array from scratch

In [19]:
zeros = np.zeros((3,4))
print("Zeros Array:\n", zeros)

ones = np.ones((4,5))
print("Ones Array:\n", ones)

full = np.full((3,3),9)
print("Constant Array:\n", full)

random = np.random.random((4,5))
print("Random Array:\n", random)
# Random always fluctuates between 0s and 1s

sequence = np.arange(0,20,3)
# sequence = np.arange(start,stop,step)
print("Sequence Array:\n", sequence)


Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Constant Array:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Random Array:
 [[0.19850763 0.82415462 0.17739805 0.39742071 0.55034089]
 [0.44446655 0.6202306  0.15310953 0.26567548 0.88874769]
 [0.3030789  0.74611382 0.04629479 0.18672154 0.82255257]
 [0.40698961 0.39421992 0.5917695  0.13215645 0.73074968]]
Sequence Array:
 [ 0  3  6  9 12 15 18]


Vector / Tensor / Matrix

In [21]:
vector = np.array([1,2,3])
print("Vector:", vector)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6], [7,8]]])
print("Tensor:", tensor)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix:", matrix)

Vector: [1 2 3]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Matrix: [[1 2 3]
 [4 5 6]]


Array Properties

In [ ]:
array = np.array([[1,2,3],
                  [4,5,6]])
print("Shape:", array.shape)
print("Dimension:", array.ndim)
print("Size:", array.size)  
# size give the total number of elements
print("Data Type:", array.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


Array Reshaping

In [29]:
original = np.arange(12)
print("Original Array:", original)

reshaped = original.reshape((3,4))
print("\n Reshaped Array:", reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array:", flattened)

raveled = reshaped.ravel()
print("\n Raveled Array:", raveled)
# Ravel returns view, instead of copy

Transpose = reshaped.T
print("\n Transposed Array:", Transpose)




Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
